/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormServerMain.java
 *
 * Created on 2009-09-07, 18:37:28
 */

package pl.n3fr0.n3Talk.showcase.server;

import pl.n3fr0.n3Talk.showcase.mirrorobjects.ContainerTableModel;
import pl.n3fr0.n3Talk.showcase.mirrorobjects.EditRectangle;
import pl.n3fr0.n3Talk.showcase.mirrorobjects.ObjectBrowser;
import pl.n3fr0.n3talk.N3Talk;
import pl.n3fr0.n3talk.core.server.Server;
import pl.n3fr0.n3talk.mirror.MirrorContainer;

/**
 *
 * @author nefro
 */
public class FormServerMain extends javax.swing.JFrame {

    /** Creates new form FormServerMain */
    public FormServerMain() {
        init();
        initComponents();

        browser = new ObjectBrowser();
        model = new ContainerTableModel(mirrorContainer);
        browser.tabObjs.setModel(model);
        panToBrowser.add(browser);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOnOff = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAddObj = new javax.swing.JButton();
        btnDelObject = new javax.swing.JButton();
        panToBrowser = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Server");
        setMinimumSize(new java.awt.Dimension(500, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        btnOnOff.setText("Start / Stop");
        btnOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnOffActionPerformed(evt);
            }
        });

        jLabel1.setText("Port#");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnOnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOnOff))
                .addGap(57, 57, 57))
        );

        btnAddObj.setText("AddObject");
        btnAddObj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObjActionPerformed(evt);
            }
        });

        btnDelObject.setText("DelObject");
        btnDelObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelObjectActionPerformed(evt);
            }
        });

        panToBrowser.setLayout(new java.awt.BorderLayout());

        btnEdit.setText("EditObject");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddObj, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelObject, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panToBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddObj)
                            .addComponent(btnDelObject))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)))
                .addGap(47, 47, 47)
                .addComponent(panToBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnOffActionPerformed
        server.start();
    }//GEN-LAST:event_btnOnOffActionPerformed

    private void btnAddObjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObjActionPerformed
        EditRectangle er = new EditRectangle(this, true);
        er.setLocationRelativeTo(this);
        er.setVisible(true);
        mirrorContainer.add(er.getRectangle());
    }//GEN-LAST:event_btnAddObjActionPerformed

    private void btnDelObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelObjectActionPerformed
        model.getRectangle(browser.tabObjs.getSelectedRow()).detach();
    }//GEN-LAST:event_btnDelObjectActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        EditRectangle er = new EditRectangle(this, true, model.getRectangle(browser.tabObjs.getSelectedRow()));
        er.setLocationRelativeTo(this);
        er.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed


    void init() {
        server = new Server();        

        n3Talk = new N3Talk();
        n3Talk.setIO(server);
        mirrorContainer = n3Talk.createMirrorContainer();

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormServerMain().setVisible(true);
            }
        });
    }

    N3Talk n3Talk;
    Server server;
    MirrorContainer mirrorContainer;
    ContainerTableModel model;
    ObjectBrowser browser;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddObj;
    private javax.swing.JButton btnDelObject;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOnOff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panToBrowser;
    // End of variables declaration//GEN-END:variables

}
